---
exclude_paths:
 - 'web/frontend/API/angular-auto-complete.js'
 - 'web/frontend/API/cast.framework.js'
 - '*.md'
 - 'api/music-metadata/**'
 - 'spec/**/*'
 - 'benchmarks/**/*'
 - '*.min.js'
 - '**/tests/**'
 - .*[\.-]min\.css
 - .*[\.-]min\.js
 - .*node_modules/.*
 - .*bower_components
 - .*vendor/.*
 - .*third[_-]?[Pp]arty
 - .*docs?/.*
 - .*samples
 - .*releases?/.*
 - .*builds
 - .*dist/.*
 - .*external
 - .*libs/.*
 - .*d3\.js
 - .*angular(-resource|)?\.js
 - .*select2(-resource|)?\.js
 - .*-ace\.js
 - .*typeahead\.js
 - .*jquery-ui\.js
 - .*reveal\.js
 - .*three\.js
 - .*chart\.js
 - .*jquery\.js
 - .*underscore\.js
 - .*lodash\.js
 - .*bootstrap\.js
 - .*bootstrap\.css
 - .*font-awesome\.css